Implement network section as button on top right corner
EyeSeeTea/3DBIONOTES pull request #105
Opened 2021-03-29 10:23 UTC by jvfdunkley

### :pushpin: References

-   **Issue:** Closes [Implement network section as button on top right corner](https://app.clickup.com/t/g55m9f)

### :memo: Implementation
- Copied over the structure and CSS from the original network tab
- Made Tools button a dropdown and Network a sub-menu
- Broke down each part of the form into its own component for (hopefully) better readability

### :art: Screenshots
<img width="1220" alt="Screen Shot 2021-03-29 at 11 39 08 AM" src="https://user-images.githubusercontent.com/20975863/112818046-64baa080-9083-11eb-8fc2-67874b6731c7.png">

### :fire: How to test it? (If there is any special consideration or the reviewer does not know how to test it)

### :bookmark_tabs: Others

-   [ ] Any change in the [API repo](https://github.com/EyeSeeTea/d2-api)? If so, what branch/PR?
-   [ ] Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

2021-03-31 11:38 UTC, tokland requested changes
Looks good! I've made a lot of suggestions and comments, but all of them are minor. Check the proposal commits for the species selector. 

Just one important thing: you have to move the changes to package.json from the other PR, right? dropzone, updated react typings and so on are missing here.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/IncludeNeighborsCheckbox.tsx
> +                onChange={() => onCheckboxChange()}
Better: `onChange={onCheckboxChange}`, which also prevents a new arrow function to be created and the prop remains immutable (important for pure components performance)

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/SpeciesSelect.tsx
> +    arabidopsisThaliana: i18n.t("Arabidopsis thaliana"),
Scientific names, we won't need translations.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkExample.tsx
> +export default NetworkExample;
As of late, we export the component without `default`. No need to change it.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkExample.tsx
> +            <small>Example</small>
i18n.t

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/Label.tsx
> +    labelText: string;
[minor] Label is implicitly a text, and in TS we have types, so usually we'd write just `label: string`.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkExample.tsx
> +        <span id="network-example" onClick={() => onExampleClick("P01111 \nP01112 \nP01116")}>
I guess we can remove the trailing space

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +}
When no arguments are required to build the initial value, we can simply: `const initialNetworkForm: NetworkFrom = {...}`

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +    const [networkForm, setNetworkForm] = useState<NetworkForm>(() => getInitialNetworkForm());
`() => fn()` -> `fn` (Caveat: unless `fn` is in fact a class-method that carries a bound context for `this`!)

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +        }
Add `TODO` somewhere in the code so we know at a glance that this is a temporal callback.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +            <Label forText="species" labelText="Select species" />
i18n.t

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +                onSpecieChange={e =>
`e` is too short, event? but's not the event, it's the species. Maybe `species` or `newSpecies`.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +            <Label forText="uniProtAccession" labelText="Enter a list of UniProt accession" />
i18n.t

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/NetworkForm.tsx
> +            <Label forText="uploadAnnotations" labelText="Upload your annotations in JSON format" />
i18n.t

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/SpeciesSelect.tsx
> +] as const;
That's a collection of names that's not really worth typing it. Note that finally you just send the parent the string (`onSpecieChange: (e: string) => void;`), so we can keep it as an string within the component. I'll make a proposal commit about this.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/UniProtAccessionTextArea.tsx
> +        ></textarea>
Small components are on the limit. Do we need a separate component or not? I think it's ok both ways.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/UniProtAccessionTextArea.tsx
> +}
As the component refers to a text area, its props can be simply `value` and `onChange`.

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/protvista/ToolsButton.tsx
> +                onClick={() => openNetwork()}
openNetwork

2021-03-31 11:38 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/network/SpeciesSelect.tsx
> +    onSpecieChange: (e: string) => void;
I think `species` it's also the singular form.

2021-04-07 06:23 UTC, jvfdunkley reviewed
All changes look good.

2021-04-07 11:19 UTC, tokland approved these changes
All good!

2021-04-07 11:20 UTC, merged