COVID19 Table minor fixes
EyeSeeTea/3DBIONOTES pull request #121
Opened 2022-02-14 11:45 UTC by p3rcypj

2022-02-17 07:52 UTC, adrianq approved these changes
From a functional point of view, this works as expected. Thanks @p3rcypj! @tokland  if you can have a quick look and check the code looks good I will merge afterwards

2022-02-17 12:27 UTC, tokland requested changes

2022-02-17 12:27 UTC, tokland commented on app/assets/stylesheets/webserver/main.css.scss
> -    position: relative;
The file has been re-formated to tabsize=2, which messes up the diff. Is it difficult to return the file to 2 spaces?

2022-02-18 09:37 UTC, tokland commented on app/assets/stylesheets/webserver/main.css.scss
> -    position: relative;
To know what the formatter is doing:vscode -> toggle panel -> output -> prettier.

The file is outside the covid project so probably vscode is using its default tabsize, simply chaning that to 4 should do the trick.

2022-02-18 10:32 UTC, tokland approved these changes
All good, thanks!

2022-02-18 10:38 UTC, merged