Add search bar styling, PDB Redo filter, auto-suggestions
EyeSeeTea/3DBIONOTES pull request #123
Opened 2022-02-18 11:56 UTC by jvfdunkley

### :pushpin: References

-   **Issue:** Closes 
 1. [Add filter to show only entries with "PDB-REDO"](https://app.clickup.com/t/245r6y5)
 2. [Redesign filters in covid page](https://app.clickup.com/t/245r5q8)
 3. [Add autosuggestion in covid search](https://app.clickup.com/t/1xprwyv)

### :memo: Implementation
- Implemented new search bar style and filters style. Filters will now be in a mini-menu and filter selections will be chips that are inside the search bar area. 
- Added PDB-Redo as a filter with Arnau's help. Because of the way the PDB-redo info is extracted on the fly, only the rendered rows have PDB-redo info. So I can only filter by PDB-redo on the page that users see. 
- Added autosuggestion and changed the search bar to an Autocomplete Material UI Lab component 

### :art: Screenshots
<img width="167" alt="Screen Shot 2022-02-18 at 12 52 00" src="https://user-images.githubusercontent.com/20975863/154678117-47d9c39a-ab2e-4a9c-af5c-cff036b72191.png">
<img width="714" alt="Screen Shot 2022-02-18 at 12 51 56" src="https://user-images.githubusercontent.com/20975863/154678120-230d6328-bedc-4833-9b9e-d96af4399c96.png">
<img width="717" alt="Screen Shot 2022-02-18 at 12 51 52" src="https://user-images.githubusercontent.com/20975863/154678121-f8ff21d6-cf18-44e9-a7e6-af4a011d9e48.png">
<img width="696" alt="Screen Shot 2022-02-18 at 12 51 48" src="https://user-images.githubusercontent.com/20975863/154678123-733bad0b-513c-4312-9897-eb9b0c9ace1c.png">

### :fire: How to test it? (If there is any special consideration or the reviewer does not know how to test it)

### :bookmark_tabs: Others

-   [ ] Any change in the [API repo](https://github.com/EyeSeeTea/d2-api)? If so, what branch/PR?
-   [ ] Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

2022-02-18 13:57 UTC, tokland reviewed
Code looks very good! I've commited some minor changes to remove a `any` type we had in there, and some other minor details. Some general comments:

- Filter -> onClick only works on the checkbox. Maybe for the full item (checkbox + label)?
- Filter -> when filters are selected/unselected, the search bar width changes, it's a bit confusing. Fixed width? (check with Adrian).
- Pagination: Should set page 1 on text or filter change [this bug was already present in the base code]
- Chip text for renders as "Pdbredo". Maybe PDB-REDO, like in the filter?

2022-02-18 13:57 UTC, tokland commented on app/assets/javascripts/covid19/src/webapp/components/structures-table/CustomCheckboxFilter.tsx
> +                            checked={filterState?.antibodies || false}
Maybe at some point `filterState` could be `undefined`, but accordingly to TS, not anymore. So: `filterState.antibodies` should work, right?

2022-02-18 13:57 UTC, tokland commented on app/assets/javascripts/covid19/src/webapp/components/structures-table/SearchBar.tsx
> +                <StyledAutocomplete
In the console appears a warning:
```
react_devtools_backend.js:4061 Material-UI: The value provided to Autocomplete is invalid.
None of the options match with `""`.
You can use the `getOptionSelected` prop to customize the equality test.
```

2022-02-19 08:07 UTC, adrianq requested changes
@jvfdunkley amazing work! On top of Arnau's comments, find below mines:
- Arnau said: "when filters are selected/unselected, the search bar width changes, it's a bit confusing. Fixed width? (check with Adrian)." -> Yes, please set the width of the textfield
- If I type something and them delete it the autosuggestion keeps "Loading" forever:
![image](https://user-images.githubusercontent.com/6850223/154792099-7baf46da-8cfa-4b39-9d61-e1a17ca45fea.png)
- In general, if I add a string that cannot be found it keeps searching forever (Loading...)
- There are some minor styling things but I will work with @p3rcypj on them

2022-02-20 16:28 UTC, adrianq approved these changes

2022-02-20 16:30 UTC, adrianq commented
Thanks @jvfdunkley for the changes! @tokland I am fine with merging this branch. Let me know if there is anything pending on your side. As I said, there are some minor things I would like to refine in terms of styling but I will work with @p3rcypj on them. Once we merge his branch

2022-02-21 09:57 UTC, tokland reviewed
The highlighting looks very good! I've committed some changes, let me know if you'd do some of that differently. Only missing the set to page=1 when necessary.

2022-02-21 14:58 UTC, tokland approved these changes
Set to page 1 working. I'll approve the PR, just a couple of notes for the next iteration:

- Check warning None of the options match with `"sapiens"`
- If the user write a search string and the clicks out of the input text, the search is lost. Maybe it should stick?

2022-02-21 21:56 UTC, adrianq commented
@jvfdunkley I think we should take care of @tokland second comment at least:
If the user enters a search string and then clicks out of the input text, the search is lost. <- It should stick
I truly think it is important to fix it to improve the user experience. Can you take care of this tomorrow?

2022-02-22 15:29 UTC, merged