Feature/setup basic infrastructure
EyeSeeTea/3DBIONOTES pull request #163
Opened 2022-06-21 08:52 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/2gq5aa6

### :art: Screenshots
<img width="819" alt="Screenshot 2022-06-21 at 09 51 47" src="https://user-images.githubusercontent.com/37223065/174759011-13c4fa33-fcb6-4c62-9841-cd67a0288a03.png">

2022-06-21 09:23 UTC, tokland requested changes
Code looking good! Just some comments inline, let me know if you have some doubts about them.

2022-06-21 09:23 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/protvista/ProtvistaPdbValidation.tsx
>      console.log("tracks", props.pdb.tracks);
I left it just as hint on where to find track info, but won't be needed for now. Let's remove it for the PR.

2022-06-21 09:23 UTC, tokland commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/protvista/ProtvistaPdbValidation.tsx
>      React.useEffect(() => {
To avoid having large component blocks, let's move the content of the useEffect to a separate function (at the bottom of the file is ok)

2022-06-21 09:52 UTC, deeonwuli commented on app/assets/javascripts/3dbio_viewer/src/webapp/components/protvista/ProtvistaPdbValidation.tsx
> +        } else {
i don't completely understand this. how is this implementation different from a full  if/else branch?

2022-06-21 13:05 UTC, tokland approved these changes
All looking good now! :+1:

2022-07-19 21:43 UTC, adrianq commented
@deeonwuli this PR can be closed, right? All the relevant features are already included in this PR https://github.com/EyeSeeTea/3DBIONOTES/pull/165 correct?

2022-09-21 11:15 UTC, closed without merging